# Generated by Django 2.2.7 on 2019-11-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191105_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='choroby',
        ),
        migrations.AddField(
            model_name='pacjent',
            name='choroby',
            field=models.ManyToManyField(to='app.Choroba'),
        ),
    ]
