# Generated by Django 2.2.7 on 2019-11-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191105_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='choroby',
        ),
    ]
