# Generated by Django 2.2.7 on 2019-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_pacjent_choroby'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='choroby',
            field=models.ManyToManyField(to='app.Choroba'),
        ),
    ]
