# Generated by Django 2.2.7 on 2019-11-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pacjent_choroby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chorobowosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choroba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Choroba')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjent_obiekt', to='app.Pacjent')),
            ],
        ),
        migrations.AddField(
            model_name='pacjent',
            name='chorobowosc',
            field=models.ManyToManyField(related_name='pacjent_choroba', through='app.Chorobowosc', to='app.Choroba'),
        ),
    ]
