# Generated by Django 2.2.7 on 2019-11-06 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dekursus_lek_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekursus_lek',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='przepustka',
            name='data_od',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wypis',
            name='data_od',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='zywienie',
            name='data_od',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
