# Generated by Django 2.2.7 on 2019-11-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191123_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgon',
            name='bezposrednia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bezposrednia_przyczyna', to='app.Choroba'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='wtorna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wtorna_przyczyna', to='app.Choroba'),
        ),
        migrations.AlterField(
            model_name='zgon',
            name='wyjsciowa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyjsciowa_przyczyna', to='app.Choroba'),
        ),
    ]
