# Generated by Django 2.2.7 on 2019-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191123_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='adres',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wypis',
            name='tryb',
            field=models.CharField(choices=[('Zakończenie procesu terapeutycznego lub diagnostycznego', 'Zakończenie procesu terapeutycznego lub diagnostycznego'), ('Skierowanie do dalszego leczenia w lecznictwie ambulatoryjnym', 'Skierowanie do dalszego leczenia w lecznictwie ambulatoryjnym'), ('Skierowanie do dalszego leczenia w innym szpitalu', 'Skierowanie do dalszego leczenia w innym szpitalu'), ('Wypisanie na własne żądanie', 'Wypisanie na własne żądanie'), ('Osoba leczona samowolnie opuściła ZOL', 'Osoba leczona samowolnie opuściła ZOL'), ('Wypisanie na podstawie art. 221 pkt 3 ustawy o ZOZ', 'Wypisanie na podstawie art. 221 pkt 3 ustawy o ZOZ'), ('Zgon pacjenta', 'Zgon pacjenta'), ('Osoba leczona, która samowolnie opuściła podmiot leczniczy', 'Osoba leczona, która samowolnie opuściła podmiot leczniczy'), ('Koniec pobytu', 'Koniec pobytu')], max_length=100),
        ),
    ]
