# Generated by Django 2.2.7 on 2019-11-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191130_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='adres',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
