# Generated by Django 2.2.7 on 2019-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191130_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='kod_oddzial_zlecajacego',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='nazwa_szpitala',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='nr_rej_szpitala',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='nr_umowy_szpitala',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='nr_wew_oddzialu',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='oddzial_zlecajacego',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='regon_szpitala',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
