# Generated by Django 2.2.7 on 2019-12-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191130_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='kod_oddzial_zlecajacego',
            field=models.CharField(blank=True, max_length=4, verbose_name='Kod oddziału VIII'),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='nr_rej_szpitala',
            field=models.CharField(blank=True, max_length=12, verbose_name='Numer rejestracyjny szpitala I'),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='nr_umowy_szpitala',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numer umowy szpitala'),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='nr_wew_oddzialu',
            field=models.CharField(blank=True, max_length=3, verbose_name='Kod oddziału VII'),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='oddzial_zlecajacego',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nazwa oddziału kierującego'),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='osoba_kontaktu',
            field=models.TextField(blank=True, verbose_name='Osoba do kontaktu'),
        ),
        migrations.CreateModel(
            name='Norton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('fizykalny', models.PositiveSmallIntegerField(choices=[('4', 'Dobry'), ('3', 'Dość dobry'), ('2', 'Średni'), ('1', 'Bardzo ciężki')], verbose_name='Stan fizykalny')),
                ('swiadomosc', models.PositiveSmallIntegerField(choices=[('4', 'Pełna przytomność i świadomość'), ('3', 'Apatia dobry'), ('2', 'Zaburzenia świadomośći'), ('1', 'Stupor lub śpiączka')], verbose_name='Stan świadomośći')),
                ('aktywnosc', models.PositiveSmallIntegerField(choices=[('4', 'Chodzi samodzielnie'), ('3', 'Chodzi z asystą'), ('2', 'Porusza sie na wózku'), ('1', 'Leżący')], verbose_name='Aktywność (przemieszczanie sie)')),
                ('samodzielnosc', models.PositiveSmallIntegerField(choices=[('4', 'Pełna'), ('3', 'Organiczona'), ('2', 'Bardzo ograniczona'), ('1', 'Całkowita niesprawność')], verbose_name='Samodzielność przy zmianie pozycji')),
                ('zwieracze', models.PositiveSmallIntegerField(choices=[('4', 'Pełna sprawność'), ('3', 'Sporadyczne moczenie'), ('2', 'Zazwyczaj nietrzymanie moczu'), ('1', 'Całkowita nietrzymanie stolca')], verbose_name='Czynność zwieraczy')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pacjent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
