# Generated by Django 2.2.7 on 2019-12-01 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191201_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='barthel',
        ),
        migrations.CreateModel(
            name='Barthel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('posilki', models.PositiveSmallIntegerField(choices=[(0, '0-nie jest w stanie samodzielnie jeść'), (5, '5-potrzebuje pomocy lub wymaga zmodyfikowanej diety '), (10, '10-')], default=0, verbose_name='Spożywanie posiłków  ')),
                ('przemieszczanie', models.PositiveSmallIntegerField(choices=[(0, '0- nie jest w stanie, nie zachowuje równowagi przy siadaniu'), (5, '5-większa pomoc. może siedzieć'), (10, '10-mniejsza pomoc'), (15, '15-samodzielny')], default=0, verbose_name='Przemieszczanie się (z łóżka na krzesło i z powrotem / siadanie)  ')),
                ('higiena', models.PositiveSmallIntegerField(choices=[(0, '0- potrzebuje pomocy przy wykonywaniu czynności osobistych '), (5, '5-niezależny')], default=0, verbose_name='Utrzymanie higieny osobistej  ')),
                ('wc', models.PositiveSmallIntegerField(choices=[(0, '0-zależny'), (5, '5-częściowo zależny'), (10, '10-niezależny')], default=0, verbose_name='Korzystanie z toalety (WC)  ')),
                ('mycie', models.PositiveSmallIntegerField(choices=[(0, '0-zależny'), (5, '5-niezależny')], default=0, verbose_name='Mycie, kąpiel całego ciała ')),
                ('poruszanie', models.PositiveSmallIntegerField(choices=[(0, '0-nie porusza się'), (5, '5-niezależny poruszający się na wózku'), (10, '10-spacery z pomocą jednej osoby, na odległość > 50m '), (15, '15-niezależny >50m')], default=0, verbose_name='Poruszanie się (po powierzchniach płaskich)  ')),
                ('schody', models.PositiveSmallIntegerField(choices=[(0, '0-nie jest samodzielny '), (5, '5-potrzebuje pomocy '), (10, '10-samodzielny')], default=0, verbose_name='Wchodzenie i schodzenie po schodach  ')),
                ('ubieranie', models.PositiveSmallIntegerField(choices=[(0, '0-zależny'), (5, '5- potrzebuje pomocy'), (10, '10-niezależny')], default=0, verbose_name='Ubieranie i rozbieranie się. ')),
                ('stolec', models.PositiveSmallIntegerField(choices=[(0, '0-nie panuje nad oddawaniem stolca'), (5, '5-przypadkowe zdarzenia bezwiednego oddawania stolca,'), (10, '10-kontroluje oddawanie stolca')], default=0, verbose_name='Kontrolowanie stolca / zwieracza odbytu ')),
                ('mocz', models.PositiveSmallIntegerField(choices=[(0, '0- nie panuje nad oddawaniem moczu, cewnik'), (5, '5- przypadkowe zdarzenia bezwiednego oddawania moczu'), (10, '10-= kontroluje oddawanie moczu')], default=0, verbose_name='Kontrolowanie moczu / zwieracza pęcherza moczowego  ')),
                ('suma', models.PositiveSmallIntegerField(null=True)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pacjent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
