# Generated by Django 2.2.7 on 2019-12-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191201_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barthel',
            name='mocz',
            field=models.PositiveSmallIntegerField(choices=[(0, '0- nie panuje nad oddawaniem moczu, cewnik'), (5, '5- przypadkowe zdarzenia bezwiednego oddawania moczu'), (10, '10- kontroluje oddawanie moczu')], default=0, verbose_name='Kontrolowanie moczu / zwieracza pęcherza moczowego  '),
        ),
        migrations.AlterField(
            model_name='barthel',
            name='posilki',
            field=models.PositiveSmallIntegerField(choices=[(0, '0-nie jest w stanie samodzielnie jeść'), (5, '5-potrzebuje pomocy lub wymaga zmodyfikowanej diety '), (10, '10-samodzielny, niezależny ')], default=0, verbose_name='Spożywanie posiłków  '),
        ),
        migrations.CreateModel(
            name='Odlezyna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lokalizacja', models.CharField(max_length=200)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pacjent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcenaOdlezyny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('stopien', models.PositiveSmallIntegerField(choices=[(1, 'I stopień – blednące po lekkim ucisku zaczerwienienie, które jest efektem reaktywnego przekrwienia.'), (2, 'II stopień – nieblednące zaczerwienienie, rumień nie ustępuje po zniesieniu ucisku.'), (3, 'III stopień – uszkodzenie pełnej grubości skóry do tkanki podskórnej.'), (4, 'IV stopień – uszkodzenie obejmuje tkankę podskórną.'), (5, 'V stopień – głębsza martwica obejmuje głębsze tkanki.')])),
                ('interwencja', models.CharField(max_length=500)),
                ('odlezyna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Odlezyna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
